#!/bin/bash

[[ $# == 0 || $1 == --help ]] && {
	echo "usage:"
	echo "./buildall <gcc-name> ..."
	exit 1
}

GCC_NAME=$1
shift

BUILDROOT=/tmp

case $GCC_NAME in
	gcc-4.6.?|gcc-4.7.?|gcc-4_6-branch|gcc-4_7-branch)
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=posix --exceptions=sjlj --arch=i686 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=posix --exceptions=sjlj --arch=x86_64 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=posix --exceptions=dwarf --arch=i686 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=win32 --exceptions=sjlj --arch=i686 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=win32 --exceptions=sjlj --arch=x86_64 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=win32 --exceptions=dwarf --arch=i686 --mingw-compress --src-compress
	;;
	gcc-4.8.?|gcc-4.9.?|gcc-4_8-branch|gcc-4_9-branch|gcc-trunk)
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=posix --bootstrap --exceptions=dwarf --arch=i686 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=posix --bootstrap --exceptions=seh --arch=x86_64 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=win32 --bootstrap --exceptions=seh --arch=x86_64 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=win32 --bootstrap --exceptions=dwarf --arch=i686 --mingw-compress && \	
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=posix --bootstrap --exceptions=sjlj --arch=i686 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=posix --bootstrap --exceptions=sjlj --arch=x86_64 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=win32 --bootstrap --exceptions=sjlj --arch=i686 --mingw-compress && \
		./build --mode=$GCC_NAME --buildroot=$BUILDROOT $@ --threads=win32 --bootstrap --exceptions=sjlj --arch=x86_64 --mingw-compress --src-compress
	;;
	*)
		echo "bad GCC name: $1. terminate."
		exit 1
	;;
esac
