--- a/Makefile	2012-03-01 15:32:36 +0400
+++ b/Makefile	2012-03-01 15:32:54 +0400
@@ -239,7 +239,7 @@ reflect:
 	@[ -n "$(THIS)" ] && $(CLEARENV) && $(MAKE) $(THIS) -e $(BUILDENV)
 
 sub_all: build_all
-build_all: build_libs build_apps build_tests build_tools
+build_all: build_libs build_apps build_tools
 
 build_libs: build_crypto build_ssl build_engines
 
