name: x86_64 and i686 release builds

on: [push, pull_request]

env:
  MINGW_BUILDS_GCC_VERSION: "16.2.0"
  MINGW_BUILDS_RT_VERSION: "v14"

jobs:
  download:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Randomly select a GNU mirror server
      shell: msys2 {0}
      run: |
        urls=("https://mirrors.ocf.berkeley.edu/gnu/" "https://mirror.techrich.hk/gnu/" "https://mirror.team-cymru.com/gnu/" "https://mirror.cs.odu.edu/gnu/")
        selected_mirror="${urls[$RANDOM % ${#urls[@]}]}"
        echo "GNU mirror server to use: $selected_mirror"
        echo "GNU_URL_PREFIX=$selected_mirror" >> $GITHUB_ENV

    - name: Download sources
      shell: msys2 {0}
      run: >-
        ./build
        --mode=gcc-$MINGW_BUILDS_GCC_VERSION
        --buildroot=/c/buildroot
        --jobs=4
        --rev=0
        --with-default-msvcrt=ucrt
        --rt-version=$MINGW_BUILDS_RT_VERSION
        --threads=mcf
        --exceptions=seh
        --arch=x86_64
        --bin-compress
        --enable-languages=c,c++,fortran
        --logviewer-command=cat
        --fetch-only
        --gnu-url-prefix=$GNU_URL_PREFIX

    - name: Compress sources
      run: 7z a src.7z src "-xr!.git"
      working-directory: c:/buildroot

    - name: Upload sources
      uses: actions/upload-artifact@v7
      with:
        path: c:/buildroot/src.7z
        compression-level: 0
        archive: false

  build:
    name: ${{ matrix.arch }}-${{ matrix.threads }}-${{ matrix.exceptions }}-${{ matrix.msvcrt }}
    runs-on: windows-latest
    needs: download
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i686]
        threads: [posix, win32, mcf]
        exceptions: [seh, dwarf]
        msvcrt: [msvcrt, ucrt]
        exclude:
          - arch: x86_64
            exceptions: dwarf
          - arch: i686
            exceptions: seh
          - threads: mcf
            msvcrt: msvcrt

    steps:
    - uses: actions/checkout@v7

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Download sources
      uses: actions/download-artifact@v8
      with:
        name: src.7z
        path: c:/buildroot

    - name: Extract sources
      run: 7z x src.7z
      working-directory: c:/buildroot

    - name: Build
      shell: msys2 {0}
      run: >-
        ./build
        --mode=gcc-$MINGW_BUILDS_GCC_VERSION
        --buildroot=/c/buildroot
        --jobs=4
        --rev=0
        --with-default-msvcrt=${{ matrix.msvcrt }}
        --rt-version=$MINGW_BUILDS_RT_VERSION
        --threads=${{ matrix.threads }}
        --exceptions=${{ matrix.exceptions }}
        --arch=${{ matrix.arch }}
        --bin-compress
        --enable-languages=c,c++,fortran
        --logviewer-command=cat

    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: bin-${{ matrix.arch }}-${{ matrix.threads }}-${{ matrix.exceptions }}-${{ matrix.msvcrt }}
        path: c:/buildroot/archives/

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        pattern: "bin-*"
        path: ./
        merge-multiple: true

    - name: Upload to Release
      id: upload_to_release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.7z"
